# Generated by Django 4.2.1 on 2023-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price_product_quantity_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_mark', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
