# Generated by Django 4.2.1 on 2023-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_person_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='created_ate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
