# Generated by Django 4.2.1 on 2023-05-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_subjects_created_ate_subjects_update_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name_plural': 'Teachers'},
        ),
    ]
